name: My first ISH-Site
favicon: null
layout_spectrum: 0.825396107044071
typography_spectrum: 0.4363895794376731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.31350288446992636
  lightness: 0.5577241082210094
  saturation: 0.3780513445381075
  rhythmicContrast: 0.01646000170148909
purpose: []
