typography_spectrum: 0.31713
color:
  brandColors:
    - '#2c2d2f'
    - '#ebebeb'
    - '#4c4d4f'
    - '#9dc33f'
    - '#848587'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3780513445381075
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.12519
analytics:
  google: null
  facebook: null
  twitter: null
name: My first ISH-Site
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: GOPRO HERO4 SILVER BUNDLE
    id: 27e06459-7a1f-4db6-8fbe-cfb627966ec7
    type: content
  - name: LG 32LE3300
    id: 82214fe7-1531-4478-9568-eb0707a9f30f
    type: content
  - name: KODAK C SERIES EASYSHARE C142
    id: 77dffc77-c62f-4d63-bf4e-5439dcd9b3ab
    type: content
  - name: GOPRO HERO4 SILVER
    id: 2cc6d35d-2679-43cc-8b55-182a6c9a2b51
    type: content
favicon: null
title: inSPIRED
description: The best resposnive starter store on the planet
purpose: []
