typography_spectrum: 0.31713
color:
  brandColors:
    - '#2c2d2f'
    - '#ebebeb'
    - '#4c4d4f'
    - '#9dc33f'
    - '#848587'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3780513445381075
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.12519
analytics:
  google: null
  facebook: null
  twitter: null
name: My first ISH-Site
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: inSPIRED
description: The best resposnive starter store on the planet
purpose: []
