name: My first ISH-Site
favicon: null
layout_spectrum: 0.58003
typography_spectrum: 0.31713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2d2f'
    - '#ebebeb'
    - '#4c4d4f'
    - '#9dc33f'
    - '#848587'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3780513445381075
  rhythmicContrast: 0.5
purpose: []
