name: My first ISH-Site
favicon: null
layout_spectrum: 0.825396107044071
typography_spectrum: 0.64225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e6f0f1'
    - '#81a1d0'
    - '#576474'
    - '#ad4000'
  brandStrength: 0.31350288446992636
  lightness: 0.5577241082210094
  saturation: 0.3780513445381075
  rhythmicContrast: 0.01646000170148909
purpose: []
